version: "3"
services:
  historical-service:
    build: .
    image: mdplus/historical-service:latest
    container_name: historical-app
    ports:
      - "8888:8888"
    environment:
      - HISTORICAL_APP_ENV=local
      - HISTORICAL_APP_HTTP_SERVER_BASE_URL=jetty:http://0.0.0.0
      - HISTORICAL_APP_HTTP_SERVER_PORT=8888
      - HISTORICAL_APP_NAME=historical
      - HISTORICAL_ORACLE_URL=jdbc:oracle:thin:@localhost:1521:ORCLCDB
      - HISTORICAL_ORACLE_USERNAME=root
      - HISTORICAL_ORACLE_PASSWORD=123456
      - XMS=2G
      - XMX=4G
